title: "My life"
date: 2021-05-29
author: KJKabangu 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Story of my life 
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
date: 2021-05-28
show_excerpts: true # set to false to remove excerpts on the homepage
